# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/data/ # https://stackoverflow.com/a/63824663
    volumes:
      - poc-data:/var/lib/postgresql/data # https://stackoverflow.com/a/41650891

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  poc-data:
